//Travel Tips.
//
//Create an array that contains the tip to show.
var Tips = {
		enunciado:"",	
};
//
//Array that contains all the travel tips.
var tip = ["Nunca te separes de tu pasaporte y mantén una copia de respaldo.",
           "Comprueba que viajas con seguro médico y que llevas a la mano los teléfonos de emergencia",
           "Aunque no hables el idioma local, aprende unas cuantas palabras y utilízalas. Nadie se reirá de ti, todo lo contrario, te lo agradecerán sinceramente.",
           "Procura siempre beber agua embotellada que hayas abierto tú mismo.",
           "Una sonrisa es la mejor manera de derribar las barreras, sean idiomáticas, culturales o religiosas.",
           "Donde fueres, haz lo que vieres.  Infórmate antes de viajar y sé respetuoso con las costumbres locales.",
           "No renuncies a comer en puestos callejeros, pero hazlo donde veas que la comida está fresca. En caso de duda, no comas nada crudo.",
           "No pierdas de vista la tarjeta de crédito, si te la exigen como garantía en un hotel, guarda las facturas hasta que termine tu viaje. En caso de algún inconveniente te será más fácil hacer una reclamación.", 
           "Comprueba antes de salir que está activado el roaming de tu teléfono y que tus tarjetas bancarias no tienen restricciones en el extranjero.",
           "Siempre lleva dinero en efectivo, nunca se sabe hasta cuándo encontrarás un cajero o cuándo se puede estropear tu tarjeta de crédito.",
           "Unos pocos dólares pueden sacarte de un apuro en cualquier país del mundo, son la moneda más internacional.",
           "Distribuye el dinero, y si aún así sufres un robo y te quedas sin nada, regístrate en un programa con el que puedas pedir dinero a tu familia desde cualquier lugar del mundo.",
           "Nunca utilices el teléfono del hotel para llamadas de larga distancia, abre una cuenta en internet para hacer llamadas y realízalas cuando encuentres wifi gratis.",
           "Cualquier destino tiene su encanto, por muy aburrido que parezca a primera vista. Deja de lado los prejuicios, y sal a conocer.", 
           "Si tienes problemas con el idioma, lleva un papelito con el nombre de tu hotel.",
           "En ciudades inseguras, no tomes un taxi en la calle, trata de tomar el del hotel o de un sitio. Los transportes colectivos suelen ser más seguros.",
           "Vístete de acuerdo al lugar que visitas y no olvides revisar el clima local.", 
           "No te muestres muy ostentoso, esto evitará que quieran aprovecharse de ti.",
           "Pide permiso antes de tomar una foto, ten en cuenta que en algunos países puede suponer una ofensa grave.",
           "Por muchas guías de viaje que lleves contigo, la mejor información siempre te la van a dar los habitantes de la localidad, pregunta sin miedo.",
           "Aunque tengas todo incluido en el hotel, haz alguna comida fuera del mismo, es la única manera de probar la gastronomía local y seguro que no te arrepentirás.",
           "Nunca des dinero a niños de la calle, muchos de ellos prefieren pedirlo a ir a la escuela. Si quieres ayudar dirígete a una ONG local.", 
           "Asegúrate de que los souvenirs que compras no vallan en contra de la ley, podrías tener problemas en la aduana.",
           "Nunca transportes encargos sospechosos, asegúrate de saber  lo que llevas contigo.",
           "Guarda lo más valioso en la caja fuerte. La hora más peligrosa es cuando se limpian las habitaciones, porque las puertas suelen quedar abiertas.", 
           "No lleves más equipaje del que puedes cargar personalmente.",
           "Lo mejor para proteger tus maletas es utilizar un candado TSA, que pueden abrir las autoridades de todo el mundo sin necesidad de romper tu candado.", 
           "Si el viaje va a durar pocos días, procura llevar todo el equipaje en cabina, te ahorrarás tiempo al llegar al aeropuerto y evitarás pérdidas innecesarias.",
           "Lleva en la cabina del avión los artículos valiosos que lleves. Por ejemplo, gafas, lentillas, cámaras o equipos informáticos.",
           "Tener en la cartera un par de fotos de credencial puede ser muy útil si tuvieras que hacer un visado imprevisto en la aduana.",
           "Disfruta intensamente de los momentos especiales. Una puesta de sol, una charla con un desconocido, son instantes mágicos que ninguna fotografía puede sustituir.",
           "Báñate, mójate, rebózate en la arena o túmbate en la hierba, viaja sin miedo a mancharte.",
           "Sea cual sea el clima de tu destino, siempre es preferible utilizar fibras naturales como algodón, lino o lana. Mejor si es de manga larga, tanto para los mosquitos como para el sol.",
           "Al atardecer y  amanecer, en los lugares con agua suele haber mosquitos. El mejor protector es el que venden en cada lugar. A veces incluso encontrarás remedios naturales mucho menos agresivos para la piel.", 
           "Comer espárragos provoca un olor especial en el sudor que repele a los insectos.",
           "Siempre que vayas a documentar, asegúrate de que anotan tu número de viajero frecuente y de que tu asiento es el que has pedido.",
           "El check in por internet te permite evitar filas y elegir el asiento que quieras si lo haces antes de las 12 horas previas al vuelo.",
           "Cuando termines de hacer la maleta, revisa de nuevo la ropa que llevas y quita un tercio, será más que suficiente.",
           "Incluye en el equipaje ropa de colores combinables entre sí, con menos prendas tendrás más conjuntos.",
           "Mete en la maleta una bolsa plegable o una mochila vacía, y deja algo de espacio libre. Lo agradecerás a la vuelta porque la ropa sucia ocupa más espacio y seguro que haces compras.",
           "Un chaleco con muchos bolsillos es la mejor forma de llevar encima todo lo que necesitas.", 
           "No seas mal pagador cuando compres algo en un mercadillo, piensa en un precio justo que puedas pagar, ten en cuenta el trabajo que lleva hacerlo y nunca abuses de la desesperación del vendedor.",
           "Trata siempre a los ciudadanos del destino como te gustaría que te tratasen a ti cuando visitan tu pueblo o tu ciudad.",
           "Los niños se aburren en los viajes, prevé juegos o dibujos para que no molesten a nadie.",
           "Busca personas mayores, siempre tienen tiempo de hablar y saben más que nadie.", 
           "Si viajas por placer, disfruta del ritmo del país, deja en casa el tuyo.",
           "Viajes solo o acompañado, un libro en tu idioma es siempre imprescindible, elígelo bien. Mejor si está ambientado en el destino o relata experiencias de otros viajeros.",
           "Aunque haga calor, unos calcetines te vendrán bien en los controles de aeropuerto o en el avión.",
           "El gorro de baño desechable del hotel es muy útil para proteger tu cámara cuando llueve o hay demasiada humedad.",
           "Lávate bien las manos antes de comer, nunca sabes con que enfermedades nuevas puedes encontrarte fuera de casa.",
           "Lleva contigo todos los medicamentos que vayas a necesitar, si es posible con receta médica para evitar problemas.", 
           "Para conocer una ciudad de verdad, visita su mercado y su cementerio.", 
           "Aléjate un par de calles de los centros turísticos, encontrarás mejores precios y un trato más personal.",
           "Si vas a estar todo el día fuera lleva contigo el cargador de tu celular, te puede salvar de una situación difícil.",
           "Hay personas perfectas para compartir la vida o una noche de fiesta,  pero no siempre son los mejores compañeros de viaje, elige bien los tuyos.",
           "Al menos una vez al año haz un viaje solo, sin pareja ni amigos, disfrutarás de sensaciones nuevas, conocerás a mucha gente y sobre todo aprenderás a conocerte mejor a ti mismo.",
           "Anota en tu agenda virtual los números de tarjetas de viajero frecuente, las vacunas que te hayas puesto y cualquier otra información importante.",
           "Antes de viajar infórmate del precio de las divisas que vas a necesitar, así sabrás valorar si el tipo de cambio que te hacen en el aeropuerto o en el hotel te conviene, o te sale mejor retirar dinero de un cajero o pagar con tarjeta.",
           "Una buena propina el primer día puede facilitarte mucho el resto de la estancia.",
           "Si el tiempo lo permite, busca productos autóctonos y un parque agradable; reserva un día para hacer un picnic urbano.", 
           "El mejor souvenir es el que se puede comer o colgar en la pared, evitarás acumular polvo en las estanterías.",
           "Cualquier producto de la gastronomía local te saldrá mucho más barato en un supermercado que en una tienda gourmet o en el aeropuerto.",
           "No descartes los autobuses, barcos o trenes turísticos, a veces son la forma más rápida y barata de ver una ciudad a grandes rasgos para luego recorrerla con calma.",
           "Si en una ciudad hay barcos turísticos, suele haber también otros mucho más baratos que utilizan los habitantes a diario.",
           "Pregunta, pregunta, pregunta. Deja a un lado la vergüenza. Preguntando a quienes viven ahí y descubrirás cosas que no vienen en las guías.",
           "Si no deshaces la maleta, no tendrás que volver a hacerla, siempre y cuando seas ordenado.", 
           "La ropa delicada se arruga menos si al hacer la maleta la metes enrollada, no doblada. Al llegar, cuélgala en una percha en el cuarto de baño. Mientras te duchas, el vapor hará un planchado de emergencia.", 
           "Si bajas a cenar o a hacer un recado rápido y dejas objetos de valor en la habitación del hotel, cuelga el cartel de no molestar, pensarán que estás dentro y evitarás tentaciones.",
           "En los climas tropicales mira bien dentro de los zapatos antes de ponértelos. Puede que se haya algún bichito dentro.", 
           "Trata a los animales que te encuentres con el mismo respeto que a las personas. Establece contacto visual, sonríe, y saluda antes de tocar.", 
           "Lleva siempre una bolsa de plástico. Puede ser muy útil para la ropa sucia o para protegerte de la lluvia.",
           "Comprar una buena maleta no es un gasto, es una inversión. No te asustes por lo que vale, al contrario pregunta cuáles son sus cualidades.", 
           "Identifica siempre el equipaje con tus datos de contacto. El teléfono que vayas a utilizar durante el viaje y un correo electrónico. No escribas datos como tu número de pasaporte, o algún otro dato que indique más sobre ti.",
           "Si tienes un vuelo largo a la vista, aprovecha para trasnochar el día anterior, el cansancio hará que caigas rendido y el vuelo se te haga mucho más corto.",
           "Al momento de regatear, ofrece la mitad del precio que te pidan y vete subiendo. Pero nunca preguntes por el objeto que te gusta, sino por uno similar.",
           "Cuando alquiles un coche en un país desconocido, pregunta por las coberturas suplementarias.", 
           "Cambia la hora de tu reloj a la del país de destino en cuanto te subas al avión, comienza desde ese momento a habituarte al nuevo horario, evitarás un poco el impacto del jet lag.",
           "Si necesitas comprar comida, hazlo antes de entrar en el aeropuerto, para evitar un gasto extra.",
           "Infórmate con antelación del precio de los visados o las tasas de entrada o salida que hayas que pagar y aparta el dinero para ello.",
           "Viajando por la noche te ahorrarás el alojamiento de ese día. Busca ofertas en los vuelos o en los trenes nocturnos.", 
           "Si necesitas un alojamiento para esta misma noche, es preferible que lo busques por Internet a que te dirijas directamente a la recepción, te puede salir más económico",
           "No te fíes de los sistemas de megafonía de los aeropuertos, en muchos no hacen anuncios. Localiza tu puerta de embarque y confirma la hora de vez en cuando.",
           "Para viajar utiliza un calzado cómodo y cerrado. Ten en cuenta que si pierdes la maleta o llega varios días más tarde será el único con el que cuentes.", 
           "En los viajes largos, utiliza ropa interior sin costuras lo más cómoda posible.",
           "Localiza y sigue las cuentas de Twitter de la compañía aérea y el hotel donde vayas a estar. Si tienes un problema de última hora suelen ser más rápidos que los servicios convencionales de atención al cliente.",
           "Si eres muy cafetero, lleva siempre en la maleta unos sobrecitos de café soluble. En muchos países lo hacen tan aguado, especialmente en los hoteles, que sin esa dosis de cafeína te dolerá la cabeza durante todo el día.",
           "Desactiva la opción de redes móviles del smartphone a menos que tengas tarifa de plan de datos en el extranjero, te evitarás sorpresas muy desagradables a la hora del pago.", 
           "Si haces compras grandes, pide que te las envíen por mensajería a casa o envíalas tú mismo, te saldrá mucho más barato que pagar el exceso de equipaje a bordo.",
           "Una libreta y un bolígrafo te serán muy útiles para anotar nombres o referencias, no hay nada más olvidadizo que un viajero.",
           "Si consideras que tu viaje es potencialmente peligroso mantente en contacto constante con alguien para que sepa que no hay inconvenientes.",
           "Deja cada lugar que visites mejor de lo que lo encontraste al llegar.",
           "No te desesperes si tienes poco dinero o poco tiempo. Viajar es mucho más fácil y barato de lo que parece." 
];
//
//Function .random that randomize the tip to display and returns the data in this. js
Tips.generarTip = function() {
	var random = Math.floor(Math.random()*100);
	Tips.enunciado = tip[random];
}